### PR TITLE
Node version warning compatible down to v0

### LINKED ISSUE #128: Misleading error message when WEBSITE_NODE_DEFAULT_VERSION is missing
When an app is missing the app setting WEBSITE_NODE_DEFAULT_VERSION, we get the following error message:

``Function (HttpTriggerJS1) Error: Failed to start language worker process for: node. node exited with code 1 console.error(`${logPrefix}Couldn't require bundle, falling back to Worker,SyntaxError: Unexpected token ILLEGAL.``

#### Investigative information

- Timestamp: 2018-09-13T22:11:16.704Z
- Function App name: jsv2tester
- Function name(s) (as appropriate): HttpTriggerJS1
- Session ID: 7aa342bd276544bda9515e5215e6c30d
- Region: West US

#### Repro steps

1. Create a function app (V2) with a node function. Delete the app setting WEBSITE_NODE_DEFAULT_VERSION.
2. Try running that function

#### Expected behavior

An error message telling me that I should set that app setting (ideally with some valid values to set it to)

#### Actual behavior

I get the error message: ``Function (HttpTriggerJS1) Error: Failed to start language worker process for: node. node exited with code 1 console.error(`${logPrefix}Couldn't require bundle, falling back to Worker,SyntaxError: Unexpected token ILLEGAL.``

#### Related information 

Setting the version to one with the correct major version, but not the correct overall version (i.e. 8.0.0) works fine.

Setting the version to one without the correct major version (i.e. 6.0.0) gives the error `Function (HttpTriggerJS1) Error: Failed to start language worker process for: node. node exited with code 1 .`

### PR DESCRIPTION
**Pull request by mhoeger**
Changing the node version warning to be very simple javascript in case very old version (v0.10.28) default is hit.

Resolves #128

### CODE REVIEW

**Comment by mhoeger** [comment]
@pragnagopa - ping! (Sorry I know you're busy with Java too!)

**Comment by pragnagopa** [comment]
Thanks for pinging. Missed the github notifcation.

File: src/nodejsWorker.ts [hunk 1]
```diff
@@ -1,9 +1,38 @@
 var logPrefix = "LanguageWorkerConsoleLog";
+var ACTIVE_LTS_VERSION = "v8";
+var CURRENT_BRANCH_VERSION = "v10";
 var worker;
+
+// Node version validation
+try {
```
Comment (pragnagopa) [inline src/nodejsWorker.ts]: Move this to a method and tests with valid versions and invalid semver versions.

**Comment by mhoeger** [comment]
@pragnagopa - I'm having a hard time coming up with a good way to test this. If I separate it out to a method, it's still really hard to test because the requiring "nodejsWorker" loads the file and runs the script (`worker = require("./Worker.js");`). I don't want to move the validation logic to a separate file that is imported and run because it would mess with how we webpack & deploy (we would need to have this validation separately dealt with and moved to the root as nodejsWorker.js is). It doesn't feel too unclean, but i'm worried about additional overhead. I think end to end testing in the future may be the best way to go

File: src/nodejsWorker.ts [hunk 2]
```diff
@@ -1,9 +1,46 @@
 var logPrefix = "LanguageWorkerConsoleLog";
+var ACTIVE_LTS_VERSION = "v8";
+var CURRENT_BRANCH_VERSION = "v10";
 var worker;
+
+// Try validating node version
+// NOTE: This method should be manually tested if changed as it is in a sensitive code path 
+//       and is JavaScript that runs on at least node version 0.10.28
+function validateNodeVersion(version) {
+    var message;
```
Comment (pragnagopa) [inline src/nodejsWorker.ts]: We do not need E2E test. A unit test would be good enough to test the logic for version verification. Yes, you are right, that we do need a E2E test that sets the node version to something that is not supported. You can add that later.

Comment (mhoeger) [reply src/nodejsWorker.ts]: It’s really hard to unit test because nodejsWorker has javascript code that executes on being loaded with ‘require’ - so every mocha test that attempts to import nodejsWorker will either fail with missing reference ‘./Worker.js’ or will run worker.startWorker. I think the way to get around this is to separate the method into a separate file and add unit tests to that exported method, but that has the challenges I mentioned above with referencing and wepacking
